$(CXX) -std=c++0x is back, enables compilation with clang
with -std=gnu++0x (llvm-clang-3.2-4.1.2 on OpenSUSE 12.3) i get:

  roman@stick ~/wc/logdemux-git 1132:0 > make check CXX=clang++
  clang++ -std=gnu++0x -pedantic -g -O2 -Wall -Wextra -Wfatal-errors -Wno-long-long -I/usr/local/include  -c -o logdemux.o logdemux.cpp
  In file included from logdemux.cpp:6:
  In file included from /usr/bin/../lib/gcc/i586-suse-linux/4.7/../../../../include/c++/4.7/memory:63:
  In file included from /usr/bin/../lib/gcc/i586-suse-linux/4.7/../../../../include/c++/4.7/bits/stl_algobase.h:65:
  In file included from /usr/bin/../lib/gcc/i586-suse-linux/4.7/../../../../include/c++/4.7/bits/stl_pair.h:61:
  In file included from /usr/bin/../lib/gcc/i586-suse-linux/4.7/../../../../include/c++/4.7/bits/move.h:57:
  /usr/bin/../lib/gcc/i586-suse-linux/4.7/../../../../include/c++/4.7/type_traits:256:39: fatal error:
        use of undeclared identifier '__float128'
      struct __is_floating_point_helper<__float128>
                                        ^
  1 error generated.
  make: *** [logdemux.o] Error 1

whereas with -std=c++0x the build passes.

-std=gnu++0x was introduced in f567b7eda03a, and since i gave it
a poor commit message it's not clear which Boost packaging / compiler
combinations were affected.